# Generated by Django 5.1.1 on 2024-11-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='codigo_verificacion',
            field=models.CharField(default=100000, max_length=6),
            preserve_default=False,
        ),
    ]
