# Generated by Django 5.1.1 on 2024-11-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_pendinguser_confirmation_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='codigo_verificacion',
            new_name='confirmation_code',
        ),
    ]
