# Generated by Django 5.0.7 on 2024-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_comentario_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Seleccione una'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
        ),
    ]
