# Generated by Django 5.0.7 on 2024-09-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_comentario_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Seleccione una'), (1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], default=0),
        ),
    ]
