# Generated by Django 5.1.1 on 2024-10-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_comentario_aprobado_por_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
    ]
