# Generated by Django 4.1.13 on 2024-10-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_comentario_anonimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.CharField(choices=[('2024-2', '2024-2'), ('2024-1', '2024-1'), ('2023-2', '2023-2'), ('2023-1', '2023-1'), ('2022-2', '2022-2'), ('2022-1', '2022-1'), ('2021-2', '2021-2'), ('2021-1', '2021-1')], default='2024-2', max_length=7),
        ),
    ]
