# Generated by Django 5.1.1 on 2024-11-11 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0003_materia_remove_profesor_materia_profesor_materias'),
        ('review', '0007_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='profesores.materia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')], default=1),
        ),
    ]
