# Generated by Django 5.1.1 on 2024-09-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='numcomentarios',
            field=models.IntegerField(default=0),
        ),
    ]
