# Generated by Django 5.1.1 on 2024-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_profesor_numcomentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calificacion_media', models.FloatField(default=0.0)),
                ('numcomentarios', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materia',
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(related_name='profesores', to='profesores.materia'),
        ),
    ]
